<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students[
  <!ELEMENT students (univ,student)>
  <!ELEMENT univ (#PCDATA)>
  <!ELEMENT student (sno,name,age,phone,address)>
  <!ELEMENT sno (#PCDATA)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT age (#PCDATA)>
  <!ELEMENT phone (#PCDATA)>
  <!ELEMENT address (#PCDATA)>
  <!ENTITY univ_address "서울 성동구 행당동 한양대학교">
  ]>
  
<students>
   <univ> &univ_address; </univ>
   <student>
        <sno> s100</sno>
        <name> 홍길동 </name>
        <age> 31 </age>
        <phone>02-234-8989</phone>
        <address> 서울시 중구 신당동 </address>
   </student>
</students>